version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/BasicCI-CD
    ignore:
      - .wget-hsts
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu
  BeforeStop:
    - location: scripts/stop_flask.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_flask.sh
      timeout: 300
      runas: ubuntu

